/**
 * main.ts - Fogbinder Entry Point
 * TypeScript wrapper for ReScript-compiled epistemic analysis engine
 *
 * Philosophy: Navigate epistemic ambiguity (late Wittgenstein + J.L. Austin)
 * NOT about removing uncertainty - about exploring it as a feature
 */

// Import compiled ReScript modules
// These will be generated by ReScript compiler as .bs.js files
import * as Fogbinder from './Fogbinder.bs.js';
import * as EpistemicState from './core/EpistemicState.bs.js';
import * as SpeechAct from './core/SpeechAct.bs.js';
import * as FogTrailVisualizer from './engine/FogTrailVisualizer.bs.js';

// Type definitions for external use
export interface AnalysisResult {
  contradictions: any[];
  moods: any[];
  mysteries: any[];
  fogTrail: any;
  metadata: {
    analyzed: number;
    totalSources: number;
    totalContradictions: number;
    totalMysteries: number;
    overallOpacity: number;
  };
}

export interface LanguageGame {
  domain: string;
  conventions: string[];
  participants: string[];
  purpose: string;
}

/**
 * Main analysis function - analyzes array of source texts
 * @param sources Array of citation texts to analyze
 * @param context Language game context (domain, conventions, etc.)
 * @returns Analysis result with contradictions, moods, mysteries, FogTrail
 */
export function analyze(
  sources: string[],
  context: LanguageGame,
): AnalysisResult {
  // Call ReScript analyze function
  return Fogbinder.analyze(sources, context, undefined);
}

/**
 * Analyze a Zotero collection by ID
 * @param collectionId Zotero collection identifier
 * @returns Promise resolving to analysis result
 */
export async function analyzeZoteroCollection(
  collectionId: string,
): Promise<AnalysisResult> {
  return await Fogbinder.analyzeZoteroCollection(collectionId);
}

/**
 * Generate human-readable report from analysis
 * @param result Analysis result
 * @returns Markdown-formatted report
 */
export function generateReport(result: AnalysisResult): string {
  return Fogbinder.generateReport(result);
}

/**
 * Export analysis to JSON
 * @param result Analysis result
 * @returns JSON representation
 */
export function toJson(result: AnalysisResult): any {
  return Fogbinder.toJson(result);
}

/**
 * Generate SVG visualization of FogTrail
 * @param result Analysis result
 * @param width Canvas width
 * @param height Canvas height
 * @returns SVG string
 */
export function generateVisualization(
  result: AnalysisResult,
  width = 1000,
  height = 800,
): string {
  return FogTrailVisualizer.toSvg(result.fogTrail, width, height, undefined);
}

// Default export
export default {
  analyze,
  analyzeZoteroCollection,
  generateReport,
  toJson,
  generateVisualization,
};

// Example usage (commented out)
/*
const sources = [
  "The meaning of a word is its use in the language.",
  "Philosophical problems arise when language goes on holiday.",
  "Meaning is determined by truth conditions.",
];

const context: LanguageGame = {
  domain: "Philosophy of Language",
  conventions: ["academic discourse", "analytic tradition"],
  participants: ["philosophers", "linguists"],
  purpose: "Understanding meaning",
};

const result = analyze(sources, context);
console.log(generateReport(result));
console.log("FogTrail opacity:", result.metadata.overallOpacity);
*/
